services:
  - type: web
    name: pinaki-portfolio-backend
    runtime: node
    rootDir: backend
    buildCommand: npm install
    startCommand: npm start
    plan: free
    envVars:
      - key: PORT
        value: 5000
      - key: NODE_ENV
        value: production
      - key: MONGODB_URI
        value: mongodb+srv://pinakisna_db_user:t5uvzzJmjBPQuok8@cluster0.5pkvnbw.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0
      - key: JWT_SECRET
        value: super_secret_futuristic_key_1337
      - key: JWT_EXPIRE
        value: 30d
      - key: RESEND_API_KEY
        sync: false
      - key: RESEND_FROM
        value: Portfolio Inquiry <onboarding@resend.dev>
      - key: EMAIL_HOST
        value: smtp.gmail.com
      - key: EMAIL_PORT
        value: 587
      - key: EMAIL_SECURE
        value: false
      - key: EMAIL_SERVICE
        value: gmail
      - key: EMAIL_USER
        value: pinaki.sna@gmail.com
      - key: EMAIL_PASS
        value: gbubjldjjlfecpuc
      - key: EMAIL_FROM
        value: pinaki.sna@gmail.com
      - key: EMAIL_TO
        value: pinaki.sna@gmail.com
      - key: ANTHROPIC_API_KEY
        sync: false
      - key: CRON_SECRET
        sync: false

